name: broadband4
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - geopandas=0.14.3
  - pandas=2.2.0
  - pyarrow=15.0.0
  - openpyxl=3.1.2
  - matplotlib=3.8.2
  - numpy=1.26.4
  - make=4.3